image: alpine

before_script:
    - apk update
    - apk add py3-pip
    - pip3 install -r requirements.txt

stages:
    - test

TestCode:
    stage: test

    script:
        - pytest

    tags:
        - common
        - cpu
